#ifndef	_RFREADERHT12E_H_ 
#define	_RFREADERHT12E_H_ 

/*
	The RF reader will decode RF packets generated by an HT12E encoder and check whether they are on the approved list
	This code is based on the work of Marcelo Shiniti Uchimura. I optimized for production use and made it interrupt driven

*/

class RFReaderHT12E{
private:	
	unsigned int *validRFCodes;
	byte noRFCodes;
	unsigned long lastPacketTS;
	unsigned int prevPacket;
	void setValidCodes(unsigned long *validCodes, byte noUsers);

public:
	RFReaderHT12E();
	void begin();
	int sizeEECfg(void);
	int loadEECfg(int address);
	void process();
	void unlockDoor(void);
	// Zero means no new codes
	unsigned int lastCode;
};

#endif