#ifndef	_RFREADER_H_ 
#define	_RFREADER_H_ 

/*
	The RF reader will decode RF packets generated by an HT12E encoder and check whether they are on the approved list
*/

class RFReader{
private:	
	unsigned long *validRFCodes;
	byte noRFCodes;
	unsigned long lastPacketTS;
	// unsigned long prevPacket;
	void setValidCodes(unsigned long *validCodes, byte noUsers);

public:
	RFReader();
	void begin();
	int sizeEECfg(void);
	int loadEECfg(int address);
	void process();
	void unlockDoor(void);
	// Zero means no new codes
	unsigned long lastCode;
};

#endif